name: time_tracking
description: Time tracking software used by millions. Clockify is a time tracker and timesheet app that lets you track work hours across projects.
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  flutter:
    sdk: flutter

  data:
    path: data
  domain:
    path: domain
  core:
    path: core
  core_ui:
    path: core_ui

  time_tracking_board_feature:
    path: features/time_tracking_board_feature

dev_dependencies:
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.15.0

flutter:
  uses-material-design: true

  assets:
    # images
    - assets/images/image-jeremy.png
    # icons
    - assets/icons/icon-ellipsis.svg
    - assets/icons/icon-exercise.svg
    - assets/icons/icon-play.svg
    - assets/icons/icon-self-care.svg
    - assets/icons/icon-social.svg
    - assets/icons/icon-study.svg
    - assets/icons/icon-work.svg
    # translations
    - assets/translations/en-US.json

  fonts:
    - family: Rubic
      fonts:
        - asset: assets/fonts/rubic/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/rubic/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/rubic/Rubik-Medium.ttf
          weight: 500
