name: passcode_navigator
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  
  get_it: ^7.2.0
  flutter_svg: ^1.0.3
  flutter_secure_storage: ^5.0.2
  flutter_bloc: ^7.3.3

flutter:
  uses-material-design: true
  assets:
  - assets/icons/

dev_dependencies: 
  dart_code_metrics: ^4.10.1
  flutter_lints: ^1.0.4
