name: access_key
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ^2.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3

flutter:
  uses-material-design: true
