name: passcode
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ^2.8.1

dependencies:
  flutter:
    sdk: flutter
  
  get_it: ^7.2.0

  data: 
    path: packages/architecture/data/
  domain:
    path: packages/architecture/domain/
  number_panel:
    path: packages/features/password_panels/number_panel/

flutter:
  uses-material-design: true
  assets:
  - assets/icons/delete/

dev_dependencies: 
  dart_code_metrics: ^4.9.1
  flutter_lints: ^1.0.4
