name: domain
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies: 
  flutter_bloc: ^7.3.3
  get_it: ^7.2.0

  data: 
    path: ../data/  

dev_dependencies: 
  dart_code_metrics: ^4.10.1   
  flutter_lints: ^1.0.4
