name: core_ui
publish_to: "none"

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.0.3
  easy_localization: ^3.0.0
  flutter_bloc: ^8.0.1
